import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  
  flowerVase,
  walClock,
  wallMounts,
  tableLight,
  showCase,
  stoneDecors,
  mirror,
  kitchen2,
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_P3300DN,
  IMPRIMANTE_PANTUM_P3300DW,
  IMPRIMANTE_PANTUM_P2509W,
  IMPRIMANTE_PANTUM_BP5100DN,
  IMPRIMANTE_PANTUM_M6559N,
  IMPRIMANTE_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,
  kitchen1,
  chimes,
  buddha,
  keyholder,
  frames,
  disney,
  krishna,
  cuttingboard,
  metalbox,
  kettle,
  fruitbasket,
  epoxy,
  speaker,
  teapoy,
  cups,
  humidifier,
  neonlight,
  tableclock,
  blackplate,
  incense,
  oildispenser,
  bottles,
  carpets,
  kidswatch,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: kidswatch,
    productName: "imprimante",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "202",
    img: imprimante2,
    productName: "imprimante",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "203",
    img: imprimante4,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "204",
    img: imprimante5,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "205",
    img: imprimante6,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "206",
    img: imprimante7,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "207",
    img: imprimante8,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "208",
    img: imprimante9,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "209",
    img: encre1,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "210",
    img: encre2,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "211",
    img: encre3,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "212",
    img: encre4,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "213",
    img: ruban1,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "217",
    img: bac1,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "220",
    img: bac3,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: flowerVase,
    productName: "Flower Vase",
    price: "30.00",
    color: "Gray",
    badge: true,
    brand: "Peacock",
    des: "A beautiful vase for your flowers.",
    cat: "Home Decor",
    pdf: pdf1,
    ficheTech: [
      { label: "Material ", value: "Ceramic " },
      { label: "Weight ", value: "450g" },

      { label: "Color", value: "Gray" },
      { label: "Height", value: "40cm" },
      {
        label: "Type ",
        value: "Water Proof ",
      },
      
    ],
  },
  {
    _id: "202",
    img: walClock,
    productName: "Wall Clock",
    price: "20",
    color: "Gold",
    badge: true,
    brand: "Seiko",
    des: "Wall Clock Gold",
    cat: "Electronics",
    pdf: pdf1,
    ficheTech: [
      { label: "Type ", value: "wall Mount" },
      { label: "Color ", value: "Gold" },

      {
        label: "Function",
        value: "Pendulum",
      },
      { label: "width", value: "30cm" },
      {
        label: "Height ",
        value: "45cm",
      },
      
    ],
  },

  {
    _id: "203",
    img: tableLight,
    productName: "Table Light",
    price: "40",
    color: "Yellow",
    badge: true,
    brand: "Philips",
    des: "Decorative Table Light",
    cat: "Home Decor",
    pdf: pdf1,
    ficheTech: [
      { label: "Material ", value: "Glass" },
      { label: "Color ", value: "Yellow" },

      {
        label: "Height",
        value: "8 Inches",
      },
      { label: "Color Mode", value: "Single" },
      {
        label: "Input ",
        value: "240V ",
      },
      { label: "Output", value: "10V" },
      { label: "Battery Support", value: "Yes" },
      
    ],
  },
  {
    _id: "2005",
    img: wallMounts,
    productName: "Hexagonal ShowCase",
    price: "39",
    color: "Wood Brown",
    badge: true,
    brand: "Shenply",
    des: "Plywood showcase",
    cat:"Home Decor",
    pdf: pdf1,
    ficheTech: [
      { label: "Material	", value: "Plywood" },
      { label: "Color", value: "Brown" },
      { label: "Type", value: "Wall Mount" },
      { label: "Weight", value: "1kg" },
      { label: "Quantity", value: "6 pcs" },
      
    ],
  },

  {
    _id: "20005",
    img: showCase,
    productName: "Vertical ShowCase",
    price: "41",
    color: "Black",
    badge: true,
    brand: "Jojo",
    des: "Vertical Showcase for Indoor and Outdoor",
    cat: "Home Decor",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin	", value: "M6559N      " },
      { label: "Marque	", value: "PANTUM      " },
      { label: "fonctions	", value: "Monofonction      " },
     
    ],
  },

  {
    _id: "206",
    img: stoneDecors,
    productName: "Stone Figures",
    price: "10",
    color: "Sandal",
    badge: true,
    brand: "King Stoneware",
    des: "Imprimante Laser PANTUM P3300DN - Fonctions: Impression - Technologie d'impression: Laser - Format Papier: A4-A5 - Vitesse d’impression: 33 ppm (A4) / 35 ppm (Lettre) - Résolution d'impression: Jusqu'à 1200 x 1200 ppp - Papier Bac d'alimentation: 250 pages - Sortie papier: 150 page - Mémoire: 256 Mo - Impression recto verso: Automatique - Heure de la première impression: Moins de 8.2s  - Taille du support: A4, A5, JIS B5, IS0 B5, A6, Lettre, Légal, Exécutif, Folio, Oficio, Déclaration, Carte postale japonaise, ZL, Big 16K, Big 32K, 16K, 32K, B6， Yougata4, Carte postale, Younaga3, Nagagata3, Yougata2 - Connecteurs: USB2.0 haut débit / Ethernet：IEEE 802.3 10/100Base-Tx - Dimensions: 354 x 334 x 232mm - Poids: 6,8 kg - Couleur: Blanc",
    cat: "Home Decor",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin	", value: "P3300DN      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Mémoire	", value: "256MO      " },
    ],
  },

  {
    _id: "207",
    img: mirror,
    productName: "Mirror",
    price: "50",
    color: "Black",
    badge: true,
    brand: "Marlo",
    des: "Full size mirror",
    cat: "Essentials",
    pdf: pdf1,
    ficheTech: [
      { label: "gtin		", value: "P3300DW      " },
      { label: "fonctions	", value: "Monofonction      " },
      { label: "Mémoire	", value: "256 Mo      " },
    ],
  },

  {
    _id: "208",
    img: kitchen1,
    productName: "Spatulas",
    price: "20",
    color: "Cream",
    badge: true,
    brand: "Solo kitchen",
    des: "silicone spatula set for cooking",
    cat: "Kitchen",
    pdf: pdf1,
    ficheTech: [
      { label: "Material	", value: "Silicone      " },
      { label: "Quantity	", value: "6" },
      { label: "Color", value: "Cream " },
      { label: "Type", value: "Medium" },
      { label: "Handle	", value: "Wood" },
     
    ],
  },
  {
    _id: "233",
    img: kitchen2,
    productName: "Dough Maker",
    price: "28",
    color: "Brown",
    badge: true,
    brand: "Soka",
    des: "Round  Dough Maker.",
    cat: "Kitchen",
    pdf: pdf1,
    ficheTech: [
      { label: "Material	", value: "Wood" },
      { label: "Color	", value: "White brown" },
      { label: "Width", value: "15cm  " },
      { label: "Type", value: "Medium" },
      { label: "Handle	", value: "Wood" },
    ],
  },
  {
    _id: "220",
    img: chimes,
    productName: "Epartswide Chimes",
    price: "25.00",
    color: "Silver",
    badge: true,
    des: "Epartswide Wind Chimes for Outside,38 Memorial Wind Chimes Large Wind Chime Deep Tone with 6 Tuned Tubes Soothing Melodic Tones Sympathy Gifts for Mom Patio Garden Dcor",
    cat: "Home Decor",
    ficheTech: [
      { label: "Material	", value: "Metal" },
      { label: "Color	", value: "Silver" },
      { label: "Mount Type", value: "String" },
      { label: "Weight", value: "25g" },
    ],
  },
  {
    _id: "221",
    img: buddha,
    productName: "Buddha Statue",
    price: "100.00",
    color: "Blue Gold",
    badge: true,
    des: "Sitting Buddha Idol Statue Showpiece for Home & Office Decor Idol Showpiece.",
    cat: "Home Decor",
    ficheTech: [
      { label: "Material	", value: "Stone" },
      { label: "Color	", value: "Blue Gold" },
      { label: "Weight", value: "879g" },
      { label: "Height", value: "8inches" },
    ],
  },
  {
    _id: "215",
    img: keyholder,
    productName: "Key Holder",
    price: "25.00",
    color: "Brown",
    badge: true,
    des: "ExclusiveLane 'Birds On Planks' Warli Handpainted Wall Keyholder .",
    cat: "Essentials",
    ficheTech: [
      { label: "Material	", value: "Wood" },
      { label: "Color	", value: "Brown" },
      { label: "Hanger Nos", value: "4" },
      { label: "Mount Type", value: "Wall" },
    ],
  },
  {
    _id: "216",
    img: frames,
    productName: "Ruban",
    price: "21.00",
    color: "Black",
    badge: true,
    des: "Art Street Primo wall photo frame Set of 11 Black Picture Frames ",
    cat: "Home Decor",
    ficheTech: [
      { label: "Material	", value: "Wood" },
      { label: "Color	", value: "Black" },
      { label: "Quantity", value: "11" },
      { label: "Mount Type", value: "Wall" },
    ],
  },
  {
    _id: "209",
    img: disney,
    productName: "Merinda Figure",
    price: "13.00",
    color: "Mixed",
    badge: true,
    brand:"Disney",
    des: "Enesco Disney Showcase Collection Merinda.",
    cat: "Home Decor",
    ficheTech: [
      { label: "Material	", value: "plastic" },
      { label: "Color	", value: "Blue" },
      { label: "Dimensions", value: "30 x 12" },
      { label: "Brand", value: "Disney" },
    ],
  },
  {
    _id: "210",
    img: krishna,
    productName: "Krishna Statue",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "eSplanade Krishna Kishan Murti Idol Statue Sculpture (5.25 inches) .",
    cat: "Home Decor",
    ficheTech: [
      { label: "Material	", value: "Glass" },
      { label: "Color	", value: "Gold" },
      { label: "Height", value: "26 cm" },
      
    ],
  },

  {
    _id: "211",
    img: cuttingboard,
    productName: "Wooden Cutting Board",
    price: "17.00",
    color: "sandal",
    badge: true,
    des: "Mango Wood Chopping Board .",
    cat: "Kitchen",
    ficheTech: [
      { label: "Material	", value: "wood" },
      { label: "Color	", value: "Sandal" },
      { label: "Dimensions", value: "30 x 40" },
    ],
  },
  {
    _id: "212",
    img: metalbox,
    productName: "Teak Wood Masala Box",
    price: "12.00",
    color: "Brown",
    badge: true,
    des: "Allure Teak Wood Masala Box .",
    cat: "Kitchen",
    ficheTech: [
      { label: "Material	", value: "Wood" },
      { label: "Color	", value: "Brown" },
      { label: "Quantity", value: "7" },
    ],
  },
  {
    _id: "213",
    img: kettle,
    productName: "Kettle",
    price: "18.00",
    color: "Mixed",
    badge: true,
    des: " Hand Painted Aluminium Tea Coffee Kettle.",
    cat: "Electronics",
    ficheTech: [
      { label: "Material	", value: "Aluminium" },
      { label: "Color	", value: "Mixed" },
      { label: "Quantity", value: "1" },
    ],
  },
  {
    _id: "214",
    img: fruitbasket,
    productName: "Metal Fruit Basket",
    price: "11.00",
    color: "Gold",
    badge: true,
    des: "Metal wire fruit basket.",
    cat: "Kitchen",
    ficheTech: [
      { label: "Material	", value: "Aluminium" },
      { label: "Color	", value: "Gold" },
      { label: "Quantity", value: "1" },
    ],
  },

  {
    _id: "217",
    img: epoxy,
    productName: "Epoxy wooden figure",
    price: "16.00",
    color: "Mixed",
    badge: true,
    des: "Mermaid Ocean Waves Beach Inspired Blue Aqua White Epoxy Resin Art with Sand Wood Wall Decor",
    cat: "Home Decor",
    ficheTech: [
      { label: "Material	", value: "epoxy" },
      { label: "Color	", value: "Blue" },
      { label: "Quantity", value: "1" },
    ],
  },
  {
    _id: "219",
    img: speaker,
    productName: "Marshall speaker",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Marshall Stockwell II Bluetooth Speaker - Black on Garmentory",
    brand:"Marshall",
    cat: "Electronics",
    ficheTech: [
      { label: "Material	", value: "Plastic nylon" },
      { label: "Color	", value: "Black" },
      { label: "Watts", value: "40W" },
    ],
  },

  // =================== imprimante hp =================

  {
    _id: "hp1",
    img: teapoy,
    productName:
      "Teak wood Teapoy",
    price: "45",
    color: "Brown",
    badge: true,
    brand: "Woodlands",
    des: "Wooden Teak wood Teapoy with basket ",
    cat: "Essentials",
    pdf: pdf1,
    ficheTech: [
      { label: "Material", value: "Wood" },
      { label: "Color", value: "Brown" },
      { label: "Brand", value: "Woodlands" },
      { label: "Max load ", value: "20kg" },
      
    ],
  },

  {
    _id: "hp2",
    img: cups,
    productName: "Cup & Saucer ",
    price: "20",
    color: "White Gold",
    badge: true,
    brand: "King Ceramics",
    des: "Goodhomes Porcelain Tea/Coffee Cup & Saucer with Gold Print (Set of 6pcs) ",
    cat: "Essentials",
    pdf: pdf1,
    ficheTech: [
      { label: "Material", value: "ceramic" },
      { label: "Color", value: "White gold" },
      { label: "Brand", value: "King Ceramics" },
      { label: "Quantity ", value: "6pcs" },
    ],
  },

  {
    _id: "hp3",
    img: humidifier,
    productName: "Xiaomi Humidifier 2 Lite",
    price: "28",
    color: "White",
    badge: true,
    brand: "Xiaomi",
    des: "Xiaomi Humidifier 2 Lite - White",
    cat: "Electronics",
    pdf: pdf1,
    ficheTech: [
      { label: "Material", value: "Plastic" },
      { label: "Color", value: "White" },
      { label: "Brand", value: "Xiaomi" },
      { label: "Quantity ", value: "1" },
    ],
  },
  // =================== imprimante ricoh =================
  {
    _id: "ricoh1",
    img: neonlight,
    productName: "Neon Wedding Signs",
    price: "38",
    color: "Pink",
    badge: true,
    brand: "Electronics",
    des: "Neon Lights Aesthetics For Your Neon Flex Decorations",
    cat: "Imprimante",
    pdf: pdf1,
    ficheTech: [
      { label: "Material", value: "Glass" },
      { label: "Color", value: "Pink" },
      { label: "Brand", value: "Bash Neons" },
      
    ],
  },

  {
    _id: "ricoh2",
    img: tableclock,
    productName: "Casio digital Clock",
    price: "59",
    color: "Black",
    badge: true,
    brand: "Casio",
    des: "Casio Black & White Beeper Sound Digital Table Alarm Clock ",
    cat: "Electronics",
    pdf: pdf1,
    ficheTech: [
      { label: "Type", value: "Digital" },
      { label: "Color", value: "Black" },
      { label: "Light", value: "Yes" },
      { label: "Quantity", value: "1" },
    ],
  },
  {
    _id: "ricoh3",
    img: blackplate,
    productName: "Black Ceramic Plates",
    price: "21",
    color: "Black",
    badge: true,
    brand: "Rose Buck",
    des: "Matte Black 6 Ceramic Plates ",
    cat: "Kitchen",
    pdf: pdf1,
    ficheTech: [
      { label: "Material", value: "Ceramic" },
      { label: "Color", value: "Black" },
      { label: "Quantity", value: "6" },
      { label: "Availability", value: "In Stock" },
      
    ],
  },
  {
    _id: "ricoh4",
    img: incense,
    productName: "Incense Burner ",
    price: "40",
    color: "Brown",
    badge: true,
    brand: "Xin Incense",
    des: "Ceramic + Wooden Lotus Incense Burner Zen Chinese Inverted Incense Holders Stand with Led",
    cat: "Essentials",
    pdf: pdf1,
    ficheTech: [
      { label: "Material", value: "Ceramic wood" },
      { label: "Battery", value: "Yes" },
      { label: "Light Modes", value: "3" },
      
    ],
  },
  {
    _id: "ricoh5",
    img: oildispenser,
    productName: " Glass Oil Dispenser",
    price: "10",
    color: "Glass",
    badge: true,
    brand: "Ricoh",
    des: "Glass Oil Dispenser - Mint",
    cat: "Kitchen",
    pdf: pdf1,
    ficheTech: [
      { label: "Material", value: "Glass" },
      { label: "Capacity", value: "1l" },
      { label: "Quantity", value: "1" },
      
    ],
  },

  // =================== imprimante ricoh =================

  {
    _id: "espson1",
    img: bottles,
    productName: "Sports water bottles",
    price: "12",
    color: "Pink Blue",
    badge: true,
    brand: "Waterware",
    des: "Sporty Motivational Water Bottles Set Of 3 Pink Blue",
    cat: "Essentials",
    pdf: pdf1,
    ficheTech: [
      { label: "Material", value: "Plastic" },
      { label: "Capacity", value: "500ml 1l 2l" },
      { label: "Color", value: "Pink Blue" },
      
    ],
  },

  {
    _id: "espson2",
    img: carpets,
    productName: "Soft Carpet",
    price: "14",
    color: "Gray",
    badge: true,
    brand: "True Fluff",
    des: "Soft Polyester Shaggy 4x6 Feet Carpet for Home Floor, Fluffy Fur Area Rug Carpets for Living Room",
    cat: "Essentials",
    pdf: pdf1,
    ficheTech: [
      { label: "Material", value: "polyster" },
      { label: "Color", value: "Gray" },
      { label: "Dimensions", value: "4 x 6 ft" },
      { label: "BabySafe", value: "Yes" },
    ],
  },
];
